clc;
clear all;
rp = 0.23;
rs = 47;
wp = 1300;
ws = 1550;
fs = 7800;
w1 = 2*wp/fs;
w2 = 2*ws/fs;
[n,wn] = buttord(w1,w2,rp,rs,'s');
[b,a] = butter(n,wn);
w = 0:0.01:pi;
[h,om] = freqs(b,a,w);
m =20*log(abs(h));
an = angle(h);
plot(w,m,om/pi,abs(h),'--');
%subplot(2,1,1);
%plot(om/pi,m);
% ylabel('Gain in dB ---->');
% xlabel('Normalised frequency ---->');
% title('Amplitude Response');
% grid on;
%subplot(2,1,2);
%plot(om/pi,an);
% xlabel('Normalised frequency ---->');
% ylabel('Phase in radians ---->');
% title('Phase Response');
grid on;